services:
  app:
    build:
      context: ./app
      dockerfile: dockerfile
    container_name: my_app
    env_file:
      - ./app/.env
    ports:
      - "3001:5173"
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - frontend

  api:
    build:
      context: ./api
      dockerfile: dockerfile
    container_name: my_api
    ports:
      - "3000:3000"
      - "5555:5555" # Expose the port for the WebSocket server
    env_file:
      - ./api/.env
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - db
    networks:
      - frontend
      - backend
  db:
    image: postgres:15
    container_name: db
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - ./api/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db_data:

networks:
  frontend:
  backend:
